### ISSUE TITLE
Editor bugs

### ISSUE THREAD

**Issue by A1Liu** [A1Liu/tci#38]
Editor is generally buggy, with highlighting being off and scrolling through large files being impossible

**Comment by Kn99HN** [comment]
Can you share a large file I can test with?

**Comment by A1Liu** [comment]
You can use `binary_search.c` in the tests folder, and if that's not long enough you can just copy-paste the entire file's contents a few times

**Comment by Kn99HN** [comment]
It seems like the editor we are using is not optimal for large files. I'm debating on either writing our own or using another library

**Comment by A1Liu** [comment]
fixed!
